basics.py
this is a basics.py file that initializes the basics of a story and then if checks if the story is expired (exceeds 24 hrs from the time you posted the story)
=> Adding file basics.py

smpost.py
This is used for adding posts at the moment with ("add_posts")
=> Added smpost.py for backend functionality

settings.py
So far code just showcases friend count
=> Add python file for app settings

r1Distilled.py
Just a basic implementation to learn by.
=> Steven branch

CommandLineBot.py
This just adds command line access to the bot and cleans up the output before printing it to terminal output. It's to make it easier to test it without modifying code every time.
=> Command line bot access

my-flask-app/loginandsignup.py, my-flask-app/uploadstory.py, my-react-app/src/storyUpload.js
This pull defines a flask blueprint named uploadstory_bp that handles story file uploads via the /api/uploadStory endpoint. It processes incoming POST requests to upload files, saves each with a unique filename based on the current timestamp, and generates metadata including the filename, upload timestamp, and expiration time set 24 hours later. The endpoint returns a JSON response containing the success message and metadata.
=> Savingmetadata mona

my-flask-app/app.py, my-flask-app/friends.py, my-react-app/.vscode/launch.json, my-react-app/src/App.css, my-react-app/src/App.js, my-react-app/src/App.test.js, my-react-app/src/index.css
This pull request includes changes to the logging in page and the creation of a python file. The logging in page changes were done to the navigation bar so as to create two separate headers for when a user logs in and before they have logged in. This owas done in the app.js and css files. The python file that was added is a rough draft code that includes the classes for adding/removing friends for users. I still need to hook it up to a database so as to save which friends have been added.
=> Creation of friend classes

LlamaRolePlay.py
This new file uses a Llama variant instead of a Deepseek variant because it seems to output a more seamless response. This required some modification of how inputs are formatted and outputs are extracted. The file adds the ability to assign (on the command line) a role to the agent and identity to the user (that the agent responds to) as well as a message that the user (identity) inputs.
=> CommandLineRole

my-flask-app/uploaddatabase.py
This pull request is to manage file upload metadata in the MySQL database. The database is initialized, creating a table containing the "uploads" folder to store information such as the filename, upload timestamp, and expiration time for each uploaded file. It also allows new metadata to be added to the database whenever a file is uploaded to ensure tracking.
=> creating and saving metadata into database

DailyForum/Backend/ForumServer.py, DailyForum/Frontend/App.css, DailyForum/Frontend/App.js
Still working on my backend. I added some fake users just to see how they interact. I will not be keeping those. 
Here are the main changes:
ForumServer
-Changed CORS handling to use flask_cors.CORS(app).
-Upgraded the data format to JSON, now storing comments with username, text, timestamp, and likes instead of just plain text.
-Renamed the comment cleanup function from remove_old_comments() to clean_old_comments() (it sounds better)
-Switched POST requests to handle structured JSON (request.json) instead of raw text.
- Added a like feature, so users can now like comments using POST /comments/like.
-Simplified GET request handling by returning jsonify(comments), removing the need for manually setting CORS headers.
-Improved validation to make sure both username and text are provided …
=> Daily Forum - Mostly backend upgrades and some features added to the frontend.

my-react-app/src/App.css, my-react-app/src/App.js, my-react-app/src/index.css, my-react-app/src/index.js, my-react-app/src/storyUpload.js, my-react-app/src/userAccount.css
In this pull request, I made adjustments to the front user login page and to the user account page. On the user account page I set up a grid layout in CSS and divided the page into five primary sections. These sections include: main content, header, footer, sidebar, and another sidebar for listing friends. The inner design still needs some reworking.
=> Changes to the style of the app

my-flask-app/postcreation.py, my-react-app/src/App.js, my-react-app/src/ViewPosts.js
Updated comments and prepped for midterm milestone :)
=> Added and updated comments for midterm milestone

my-flask-app/tempPython.py, my-flask-app/uploadstory.py, my-react-app/src/storyUpload.js, my-react-app/src/userAccount.css
Starting on the frontend layout of stories. I retrieved and displayed the uploaded file within a circular container after a successful upload. Idea was to allow users to view the uploaded file in the frontend by fetching it from the server. Ensured the proper URL for the constructed file and passed it to the frontend to display uploaded image.
=> Beginning of frontend layout mona

my-react-app/package-lock.json, my-react-app/src/dailyForum.js
Code is not quite working yet. Added the button and the box but it doesn't really let you reply. I need to see what I am doing wrong with it.
=> reply to individual comments

my-react-app/src/App.js, my-react-app/src/dailyForum.css, my-react-app/src/smallerPage.css, my-react-app/src/userAccount.css
Changed the appearance of the the post page. Also tried to add screen shrinking but it doesn't work quiet right yet...
=> CSS styling

LlamaRolePlay3.py, dbDataset.csv
Custom Fine Tuned Chatbot with RAG functionality and dbDataset.csv for RAG to draw data from.
=> Custom Fine Tuned Chatbot with RAG functionality

package.json
added typescript config to package.json file
=> most recent verison of package.json

my-flask-app/postcreation.py, my-flask-app/poststesting.py, my-react-app/src/ViewPosts.js
-  Removed Redundancy of code from all Codebases
- Removed Excessive Console Logs (Debugs Perhaps)
- Testing File for Posts, testing API Responses in WhiteBox, BlackBox, Integrations Testing
- Simplified code
- Resolved empty posts from being created
=> Code cleanup and bug fixes for Posts Section

my-flask-app/uploadstory.py, my-react-app/src/storyUpload.js, my-react-app/src/userAccount.css
Previously, image uploads were only allowed. This pull request focuses on allowing video uploads. Certain extensions must be present to upload the video. The video is shown as a preview before uploading. Video stories post-upload is still in the works. Additionally, I added slightly different style features for the story section. Lastly, some code was cleaned up and organized.
=> Allowed video preview upload

my-flask-app/ForumServer.py, my-flask-app/loginandsignup.py, my-react-app/src/App.js, my-react-app/src/dailyForum.js
reply to comment is now working
=> Fixed reply

my-flask-app/postcreation.py, my-react-app/src/ViewPosts.js
Displays repost count when a user or many users have reposted the same post
=> Display repost count next to posts

my-flask-app/loginandsignup.py, my-react-app/src/App.js, my-react-app/src/HomePage.js, my-react-app/src/storyUpload.js
Previously, when the refresh or back arrow button was clicked, the program would return to the login page. I fixed this functionality by first checking if the user is authenticated on page load, then redirecting to the home page after sign-up, and persisting the authentication status. However, if not authenticated, then I show the login page. I ensure the user stays logged in even after refreshing the page unless they log out. The only way to log out is by clicking the "logout" button in "Settings"
I additionally added a route where if the user wants to upload a new story, all story functionality gets moved to another page, and when "upload" is pressed, we return to the home page.
=> Refresh functionality

my-react-app/package-lock.json, my-react-app/package.json, my-react-app/src/App.js, my-react-app/src/HomePage.js, my-react-app/src/dailyForum.css
Still working on getting the username to transfer and making the forum bigger
=> Moved Forum

my-flask-app/postcreation.py, my-react-app/src/ViewPosts.js
Added where users can undo reposts if they don't want it reposted anymore.
=> Added Undo Repost Feature

my-flask-app/uploadstory.py, my-react-app/src/HomePage.js, my-react-app/src/storyUpload.js
Implemented a file upload feature in React that displays the uploaded image on the homepage, instead of the sub-page (that was created in the last PR). The StoryUpload component handles the selected file and uploads it to a server using an HTTP POST request. Once the upload is successful, the uploaded stories metadata is added to the uploadedStories state where the page, then, navigates back to the homepage. On the homepage, the list of uploaded stories is displayed as image circles.
=> Showing upload image on homepage

my-flask-app/BotServer.py, my-react-app/src/botFront.js
This just adds a couple of lines of comments in BotServer.py and botFront.js to accredit ForumServer.py and dailyForum.js (and their respective authors by implication), since BotServer.py and botFront.js are substantially modeled after  ForumServer.py and dailyForum.js respectively.
=> Forgot something

my-react-app/src/HomePage.js, my-react-app/src/botFront.js
Just changed Bot Forum to Chat Forum in HomePage.js and botFront.js
=> Chat forum not bot forum

my-react-app/src/App.js, my-react-app/src/botFront.js, my-react-app/src/user-profile.css, my-react-app/src/userAccount.css, my-react-app/src/userProfile.js
Here is what I added to the user profile page =
- Grid layout design
- User can update profile pic
- User can update background photo
- Background photo has a default edit button that appears
- Background photo and profile pic are stored locally, will need to figure out how to implement this into a database
=> Added more design elements to the user profile page

my-flask-app/package.json, my-flask-app/postcreation.py, my-react-app/package-lock.json, my-react-app/package.json, my-react-app/src/ViewPosts.js
- Added a likes and comment functionality
=> Add like and comment feature to posts

my-flask-app/uploaddatabase.py
add edge case - if database does not exist, create it
=> creating db if dne

playwrite2.py
Bot now access Daily Forum without using or needing to know any other project code.
=> Bot accesses to the Daily Forum

my-react-app/src/App.js, my-react-app/src/HomePage.js, my-react-app/src/SettingsPage.css, my-react-app/src/SettingsPage.js
Updates:
-Created link to setting page in App.js 
-Edited Settings drop down menu
-Created box design layout for the settings page
-Got the login and Account Detail button working
-Did not get the update password/username buttons working yet, having trouble hooking up to database and updating
-Small tweaks in App.js to improve cleanliness. 
-Might change the Account detail button to just load up to a new page that stores the username, password, profile, and background photo from the user Profile page.
=> Creation of the settings page layout design and functionality

my-flask-app/ForumServer.py, my-flask-app/loginandsignup.py, my-react-app/src/App.js, my-react-app/src/HomePage.js, my-react-app/src/chatAi.css, my-react-app/src/dailyForum.css, my-react-app/src/dailyForum.js, my-react-app/src/userProfile.js
Link to user profile and display userpic too
=> Username changes

my-flask-app/chatAi.py, my-react-app/src/chatAi.css, my-react-app/src/chatAi.js
Chat now displays userprofile pic
=> Changes to chatAi

playwright4.py
The playwright3.py file runs by finding the 2nd <p> in the css as the prompt. The new profile pic functionality hides the first <p> (user name) away under the "profile header" class, so the 1st <p> needs to be found instead.
=> Update playwright file after profile pics

my-react-app/src/HomePage.js, my-react-app/src/storyUpload.js
added more advanced functionalities and display of story
=> Editingdisplay

my-react-app/src/App.css, my-react-app/src/HomePage.js
=> Sidebar links

my-react-app/src/story.css, my-react-app/src/storyUpload.js
improved the UI/frontend design of the story page
=> Storypage UI
